services:
  front-end:
    build:
      context: ./front-end
    depends_on:
      - express-server
    ports:
      - "3000:3000"
    env_file:
     - ./front-end/src/.env
  express-server:
    build:
      context: ./express-server
    ports:
      - "5000:5000"
  collector:
    image: lark9042/otelcol-custom:0.1.0
    ports:
      - "4318:4318"
    depends_on:
      cassandra:
        condition: service_healthy
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 10s
      timeout: 5s
      retries: 5
